version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - target-branch: release-1.12
    package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - target-branch: release-1.12
    package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: istio/proxyv2
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - target-branch: release-1.11
    package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - target-branch: release-1.11
    package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: istio/proxyv2
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

